//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mboss.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mboss.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of Mandatory data not provided.
        /// </summary>
        public static string MBS01DEF10001 {
            get {
                return ResourceManager.GetString("MBS01DEF10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the Data has validation issues.
        /// </summary>
        public static string MBS01DEF10002 {
            get {
                return ResourceManager.GetString("MBS01DEF10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Data.
        /// </summary>
        public static string MBS01DEF10003 {
            get {
                return ResourceManager.GetString("MBS01DEF10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string MBS01DEF10004 {
            get {
                return ResourceManager.GetString("MBS01DEF10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Updated Successfully.
        /// </summary>
        public static string MBS01DEF10005 {
            get {
                return ResourceManager.GetString("MBS01DEF10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed, Please try again or contact administrator.
        /// </summary>
        public static string MBS01DEF10006 {
            get {
                return ResourceManager.GetString("MBS01DEF10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response receive from the server, please contact administartor.
        /// </summary>
        public static string MBS01DEF40000 {
            get {
                return ResourceManager.GetString("MBS01DEF40000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the the User ID. Please contact Administrator.
        /// </summary>
        public static string MBS01LOG10001 {
            get {
                return ResourceManager.GetString("MBS01LOG10001", resourceCulture);
            }
        }
    }
}
